### ISSUE TITLE
[Add Miner] miniz

### ISSUE THREAD

**Issue by platinum4** [Quake4/MindMiner#358]
https://miniz.ch/download/

**Comment by platinum4** [comment]
No I just saw that @nemosminer was using this.

**Comment by platinum4** [comment]
This appears to be faster now, please see this link https://github.com/nemosminer/NemosMiner/commit/e8e0b1702c2a8bdc698df136b8235ab1d66ba89f

**Comment by Quake4** [comment]
just try it self and post speed between gminer

**Comment by mo35** [comment]
miniZ miner v1.2l

https://miniz.ch/download/
 * Support for Equihash 192,7 (ZER, SAFE, GENX, VDL, ZERC).
 * miniZ GUI Launcher v1.0. (Windows)
 * Minor speed improvements for 144,5.
 * Fixed --intensity option. Express in percentage [0,100].
 * Other bug fixes.

**Comment by mo35** [comment]
miniZ v1.2m

 * Speed improvements for 144,5 and 192,7. Major boost for RTX GPUs.
 * Fee shares excluded from statistics.
 * --show-pers to show personalization string.
 * --smart-pers to use personalization string ‘auto’ if available, otherwise use specified pers. For compatibility with Mining Rig Rentals.
 * --show-solratio to show number of solutions per iteration.
 * --oc1/--oc2 for boost in performance when applying OCs to GPUs.
 * Help with new look. Run miniZ.exe --nocolor --help to exclude colors (Win7).
 * Improved stability.
 * Other bug fixes.

**Comment by Quake4** [comment]
added
