### ISSUE TITLE
Add power consumption accounting

### ISSUE THREAD

**Issue by Quake4** [Quake4/MindMiner#54]
Nvidia-smi and amd???

**Comment by podlbo** [comment]
Something simmilar uses MegaMiner from Tutulino...
https://github.com/tutulino/Megaminer
He uses nvidia SMI for nvidi cards for AMD i dont know how he implement this...

**Comment by platinum4** [comment]
https://github.com/UselessGuru/MultiPoolMiner/blob/master/Include.psm1

**Comment by Quake4** [comment]
Thanks.

**Comment by Quake4** [comment]
yet in the very distant plans

**Comment by platinum4** [comment]
need do

**Comment by platinum4** [comment]
do, professional programme

**Comment by platinum4** [comment]
Please add this.

**Comment by platinum4** [comment]
We've come about 5 months now with no real progress on this.  You are smart enough to add this.  You just need to add new stats values for all miners that incorporate power draw only; so instead of GetSpeed, also make a GetPowerDraw and then make that function dump stat.txt files in /Stats/ that would say lets say ccminer-trex-072_power_draw and then in that file be a JSON just like you make for hashrates.

Power draw can be pulled from SMI or even some miners' APIs now.  Please add this it would make your miner very much more complete.

**Comment by Quake4** [comment]
Yes. No progress. I don't have time to write and debug this needed code.

**Comment by platinum4** [comment]
Hi,

I see you pulled NV-SMI info on v3.13, now all you need do is add stat category of power draw and build .txts for powerdraw same json format; you are over 85% here already-- then have in config place for us to put electricity cost and it will calculate how many kWh/day * cost of electricity to see if it is above Lower Floor or not
